version: '3'

networks:
  docker-practice-net:
    driver: bridge

services:

  app:
    build:
      context: ../..
      dockerfile: ./ops-tools/docker/images/app/Dockerfile
    ports:
      - "8888:8080"
    command: sh -c "mvn package; java -jar target/docker-practice-java-0.0.1-SNAPSHOT.jar"
    networks:
      - docker-practice-net
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:14.5-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=school
      - POSTGRES_USER=postgres
      - POSTGRES_DB=school
    volumes:
      - ../../data/postgres:/var/lib/postgresql/data
      - ../../data/dump:/db-dump
    networks:
      - docker-practice-net
    ports:
      - "5432:5432"

  redis:
    image: redis:7.0.4-alpine
    restart: always
    networks:
      - docker-practice-net
    ports:
      - "6379:6379"
